### ISSUE TITLE
Missing the `_jupyter_nbextension_paths()` method.'

### ISSUE THREAD

**Issue by nicolaspoulain** [parmentelat/nbautoeval#10]
$ pip3 install nbautoeval

is ok but nbautoeval installation raises an issue 

$ jupyter-nbextension  install nbautoeval --py --sys-prefix

Traceback (most recent call last):
  File "/home/nico/.local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/nico/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/nico/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/nico/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/nico/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 257, in start
    self.subapp.start()
  File "/home/nico/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/home/nico/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 690, in install_extensions
    **kwargs
  File "/home/nico/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 206, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/nico/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 1120, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module nbautoeval is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'

**Comment by parmentelat** [comment]
Hello Nicolas

nbautoeval does depend on Jupyter, to the extent that it produces an html fragment, that a regular Python process would not be able to render easily

However, nbautoeval is pacakged as a **regular Python module**, and **not a Jupyter extension**, so it is quite expected that the command you are trying to run is not succeeding :)

If the documentation is unclear in that respect, please tell me what part of the doc has left you with the wrong impression
